LANGUAGES = {
    "English": {
        "select_language": "Please select your language:",
        "main_menu": "Main Menu:",
        "rest_api": "REST API",
        "enter_name": "Please enter your name:",
        "enter_surname": "Please enter your surname:",
        "enter_student_id": "Please enter your student ID:",
        "enter_contact": "Please enter your contact number:",
        "select_payment": "Please select your preferred payment method:",
        "thank_you": "Thank you! Your details have been saved.",
    },
    "Русский": {
        "select_language": "Пожалуйста, выберите язык:",
        "main_menu": "Главное меню:",
        "rest_api": "REST API",
        "enter_name": "Пожалуйста, введите ваше имя:",
        "enter_surname": "Пожалуйста, введите вашу фамилию:",
        "enter_student_id": "Пожалуйста, введите ваш студенческий номер:",
        "enter_contact": "Пожалуйста, введите ваш контактный номер:",
        "select_payment": "Пожалуйста, выберите предпочтительный способ оплаты:",
        "thank_you": "Спасибо! Ваши данные были сохранены.",
    },
    "O‘zbek": {
        "select_language": "Iltimos, tilni tanlang:",
        "main_menu": "Asosiy menyu:",
        "rest_api": "REST API",
        "enter_name": "Iltimos, ismingizni kiriting:",
        "enter_surname": "Iltimos, familiyangizni kiriting:",
        "enter_student_id": "Iltimos, talaba raqamingizni kiriting:",
        "enter_contact": "Iltimos, telefon raqamingizni kiriting:",
        "select_payment": "Iltimos, to‘lov usulini tanlang:",
        "thank_you": "Rahmat! Ma'lumotlaringiz saqlandi.",
    },
}
